### ISSUE TITLE
New game does not get created

### ISSUE THREAD

**Issue by shoenig** [samcf/hnefatafld#8]
I'm not sure what I'm doing wrong (no nginx setup?), but pushing Start on /game takes me to something like
    http://localhost:8000/game/xBOwPv6Pl2gn

but the Share URL is blank and Turn to play: fields are blank

**Comment by samcf** [comment]
This is most definitely a nginx setup issue. The app hosts the HTTP and WS servers on different ports and my client uses nginx to reverse proxy / to the HTTP server and /ws to the WS server. I thought this was a good idea out of hand, but maybe that's looking slightly over-engineered right now.

I really like running nginx in front of the application, but it's less than ideal for development environments. Any idea how I can write a fallback within Go? Or do you think I should just shove everything in the same port and use the Go server directly? I will check out your daemon PR to see if that can solve this problem more elegantly.
